### ISSUE TITLE
Make "ResultsPath" and "active" user options

### ISSUE THREAD

**Issue by maaaaz** [JoshuaMart/AutoRecon#11]
Hello,

Instead of having to specify `"ResultsPath"` and uncomment the ["amass active"](https://github.com/JoshuaMart/AutoRecon/blob/master/recon.sh#L46) option in the script, can you make them user options ?
It would be more convenient.

Cheers !

**Comment by JoshuaMart** [comment]
I added the `-rp` option to specify the folder. The comment on "amass active" is an error on my part, I removed the comment in the last update
