### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by saberzaid** [JoshuaMart/AutoRecon#13]
Recon is in progress, take a coffee
>> Amass is in progress
>> Github-Subdomains.py is in progress
usage: github-subdomains.py [-h] [-t TOKEN] [-d DOMAIN] [-e] [-s] [-v]
github-subdomains.py: error: auth token is missing
>> Aquatone is in progress

hello i think this is a bug , also the Nuclei and others tools not starting after the Aquatone finish

**Comment by JoshuaMart** [comment]
Hello,
I think your first concern is that you didn't enter an API key.
```
Create the file .tokens in /root/Tools/Github-Subdomains/ with one or more github token.
```

For Nuclei, I did an update for the past in version 2, I advise you to reinstall it to check.

I have checked on my side, the script is running without any problem.

Regards

**Comment by saberzaid** [comment]
Ok thank you

I have suggestions , can you add port scan for all the url list that only show the port number and the service name like nmap what shows in -pn command 

And if find for example smb port open it will do smb attack such as file sharing  , and if found ftp port it will login as anonymously etc 

Thank you

**Comment by JoshuaMart** [comment]
I take your suggestion into account, I'll see how the [Rengine](https://github.com/yogeshojha/rengine/) project evolves first :)

**Comment by saberzaid** [comment]
Hi again

I try rengine , its still in very early development 

I think autorecon can do better in the cli side by adding gobuster or dirsearch and smbclient and some tools to be all in one recon in single enter click 

Thanks for your support and hv a nice day
